### ISSUE TITLE
Archive only selected tasks

### ISSUE THREAD

**Issue by fipke** [aziz/PlainTasks#178]
I Would like to archive only some tasks (Selected Tasks), and not all completed tasks.
Is it possible?

**Comment by r44083** [comment]
I agree with fipke, it is a very useful feature!

**Comment by diogolr** [comment]
This fix (commit [c58dbe3](https://github.com/aziz/PlainTasks/commit/c58dbe3a0d5544c5e62b336a4205de27f866e279)) is deleting previous archived tasks. A friend of mine (@victoraraujo01) have already implemented a "plugin" without this issue.

Can he submit a new pull request?

[PlainTasksArchiveSelected.zip](https://github.com/aziz/PlainTasks/files/677071/PlainTasksArchiveSelected.zip)

**Comment by vovkkk** [comment]
> deleting previous archived tasks

Could you open console (in main menu View→Show Console) and tell me what’s there when archiving deletes previous tasks?



> A friend of mine (@victoraraujo01) have already implemented a "plugin" without this issue.
> 
> Can he submit a new pull request?

If the difference is commenting `self.view.run_command('plain_tasks_sort_by_date')` (the only difference I can see so far) then, no it is not the way to fix it.

**Comment by diogolr** [comment]
> Could you open console (in main menu View→Show Console) and tell me what’s there when archiving deletes previous tasks?

The console shows me nothing :(

> If the difference is commenting `self.view.run_command('plain_tasks_sort_by_date')`

Yeah, commenting this line works like a charm...

**Comment by vovkkk** [comment]
Can you show me those deleted tasks?

**Comment by diogolr** [comment]
Here is a step by step archiving...

Defining tasks
![image](https://cloud.githubusercontent.com/assets/4297658/21544994/a8113936-cdb2-11e6-96a3-aad71e4f1e47.png)

Marking as done
![image](https://cloud.githubusercontent.com/assets/4297658/21544999/b069a5e6-cdb2-11e6-9355-7bcfce385a99.png)

Archiving with `ctrl+shift+a` (Perfect)
![image](https://cloud.githubusercontent.com/assets/4297658/21545012/cc37517e-cdb2-11e6-94f1-8e761202d369.png)

Marking as done again
![image](https://cloud.githubusercontent.com/assets/4297658/21545226/94f64218-cdb4-11e6-9624-b0ef85933081.png)

Archiving only (archive within selection) `Project 2 -> Subject 1 ->Task 2`
![image](https://cloud.githubusercontent.com/assets/4297658/21545250/d52f68f0-cdb4-11e6-90f5-90b5e244b94d.png)

Result:
![image](https://cloud.githubusercontent.com/assets/4297658/21545268/f21f95b6-cdb4-11e6-8b0b-be46a8a8074f.png)

**Comment by victoraraujo01** [comment]
Ok, so from what I can tell, the problem here is the way the `find_all` function is called inside the `SortByDate` command. In the PlainTasks.py, it is being called like this (https://github.com/aziz/PlainTasks/blob/0aa7e15845d7de0c9dd4f5a1b102a3a5e47422f4/PlainTasks.py#L642):

`self.view.find_all(have_date, archive_pos.b-1, "\\2\\1", tasks_prefixed_date)`

From this call I presume the intention was to find all matches of the `have_date` regexp after `archive_pos`. However, take a look at the documentation for this function in the Sublime Text 3 API (https://www.sublimetext.com/docs/3/api_reference.html):

`find_all(pattern, <flags>, <format>, <extractions>)`
*Returns all (non-overlapping) regions matching the regex pattern. The optional flags parameter may be sublime.LITERAL, sublime.IGNORECASE, or the two ORed together. If a format string is given, then all matches will be formatted with the formatted string and placed into the extractions list.*

So, the second argument is supposed to be the flags used in the find operation, not its start point (as is the case for the similar `find` function). When I replaced this line with the following two lines, the problem was solved (at least for me).

`tasks = self.view.find_all(have_date, format="\\2\\1", extractions=tasks_prefixed_date)`
`tasks = list(filter(lambda t: t.begin() > archive_pos.end(), tasks))`

**Comment by vovkkk** [comment]
Yes, you are right about reasons.
But the actual solution should be following, because we must filter the extractions list as well, I am about to commit it

```python
            all_tasks_prefixed_date = []
            all_tasks = self.view.find_all(have_date, 0, u"\\2\\1", all_tasks_prefixed_date)

            tasks_prefixed_date = []
            tasks = []
            for ind, task in enumerate(all_tasks):
                if task.a > archive_pos.b:
                    tasks.append(task)
                    tasks_prefixed_date.append(all_tasks_prefixed_date[ind])
```

**Comment by diogolr** [comment]
Well done! Everything (including sorted dates) works now :+1:
