### ISSUE TITLE
Feature Request: Show a summary of all open actions in a given file

### ISSUE THREAD

**Issue by skarfacegc** [aziz/PlainTasks#209]
It would be awesome to have some way to see a list of all uncompleted tasks in a given file.  I like to use plaintasks to take notes and capture actions, the ability to quickly see any outstanding actions in the file without the rest of the text would be super useful

**Comment by psidnell** [comment]
It doesn't quite do what you want but I've just discovered the [Filter Lines](https://github.com/davidpeckham/sublime-filterlines) plugin which can fold all the lines except for those you specify in a text/regex search.

So for example you could fold all lines except those with "@started" on them and it would show only those lines.

**Comment by vovkkk** [comment]
I did not see this issue early, which is strange.

Speaking of pending tasks, it seems very specific and would not make sense for average user, because, I believe, 90% of a doc content would be pending tasks for average user.
But you can create your own plugin in User folder, it should be simple (I did not test it):

```python
from PlainTasks.APlainTasksCommon import PlainTasksFold


class PlainTasksFilterPending(PlainTasksFold):
    def run(self, edit):
        self.exec_folding(self.view.find_by_selector('meta.item.todo.pending'))
```

Speaking of filter by tag(s), you can now just select tags, click RMB, and choose filter in menu.
