### ISSUE TITLE
Feature Request: Make the dot optional on file paths

### ISSUE THREAD

**Issue by macdrifter** [aziz/PlainTasks#223]
To improve compatibility for relative file paths in applications like nvALT and Editorial for iOS, it would be nice if the preceding dot and ending slash on file paths was optional.

Instead of ```./dir1/dir2/filename.txt/``` I'd like to use ```dir1/dir2/filename.txt```

A minor problem but it would make them behave more like standard links.

**Comment by vovkkk** [comment]
Well, the only question is regex that allow to support related features.
I mean, for instance, why there is preceding dot? because it would allow to make highlighting links, i.e. differentiate them from case when slash used in place of ‘or’ `this/that` (I admit that since that plan a lot of time has passed, but still we can add highlighting… eventually).
Or why there is ending slash? because filename may contain whitespace; and user may want to add some arbitrary text *after* link—so [back]slash is explicit delimiter of filename.

**Comment by macdrifter** [comment]
Sure. I get it. Same reason Markdown uses ```[anchor](url_link)``` to specify the start and stop of the URL. In an application like nvALT, this is handled by specifying a base URL for the preview template. Then links to relative file paths can be included and anchored but also be designated separate from other text. URLs that lack a protocol part (i.e. http) are assumed to be relative file links. 

Something to think about. Rely on the standard Markdown syntax but add a new config for handling linking to relative file paths. For example:

```"relative_file_path": "/dir1/dir2/"```

Then adding a link like ```[Some anchor text](my reference file.txt)``` would allow for opening the file at ```./dir1/dir2/my reference file.txt```

Just an idea.

**Comment by vovkkk** [comment]
Well, currently file links can be
* absolute path
* relative to any project folder
* relative to any opened file

And syntax is just of placing path between dot and [back]slash—very simple, but not compatible with other formats.
So I don’t know… Markdown, Org-Mode, etc., all have different syntaxes for file links (arguably more complex than PT one)—so should we support all of them? that’s too much work; but then maybe just one of them? which one? and why the one instead of another?

**Comment by macdrifter** [comment]
I don't have a strong argument for one over the other that doesn't involve my personal preference. Markdown seems more common and you support Markdown for bold and italic already. But Org-Mode link format is fine too. I think my issue with the current format is that it uses start and stop characters that are also common characters used in file paths. It's also not consistent when it refers to a specific section of a linked document because it lacks the closing forward slash.

The only argument I could see for Markdown link format is that there are other Sublime packages that could also leverage the syntax and still work well with the list format of PT (although they require link text to be in square brackets. The OM support for links is powerful but I don't think there's any other way to use them in Sublime. But I think either format would work.

These are just comparisons of the syntax:

```
[](dir1/dir2/some file name.txt)
[[dir1/dir2/some file name.txt]]
.dir1/dir2/some file name.txt/
```
For linked text, if you do go with OM syntax I'd recommend changing your separators too.

```
[](dir1/dir2/some file name.txt"some linked text")
[[dir1/dir2/some file name.txt::some linked text]]
.dir1/dir2/some file name.txt"some linked text"
```

**Comment by vovkkk** [comment]
I’ve add support for Markdown-style links in separate branch https://github.com/aziz/PlainTasks/tree/x-223-md-links
Not push to master, just to make sure if this makes sense, @macdrifter let me know what you think.

**Comment by macdrifter** [comment]
I kind of like it, which I'm sure is totally biased. Here's some comparisons (note, I use a custom syntax of ```{>>some text<<}``` for linking to document sections so that I'm sure the text is unique and stands out):

```
		./SupportDocuments/supWork.md"{>>ChemReg<<}"
		[support doc](/SupportDocuments/supWork.md"{>>ChemReg<<}")
		[support doc](SupportDocuments/supWork.md)
		[](SupportDocuments/supWork.md)
```

First is the original format. Second is Markdown with an anchor and matching line text. Third is anchor with just a file link. Last is just an empty Markdown anchor link. I like that the preceding slash is optional in this case.

My original comment about compatibility with other Markdown packages is not valid. Because the text is indented, it's treated as a code block so the markdown link is ignored.
