### ISSUE TITLE
Feature: Folding also on comments

### ISSUE THREAD

**Issue by benignoc** [aziz/PlainTasks#238]
Hello,

Thank you for your plugin, it is really neat and I am starting now to use it. I am wondering if it would be possible to include the folding also on comments and not only on subtasks or projects.

Comments are useful to anotate the tasks, but they become noise when trying to look at the tasks list.

Thanks for considering, and sorry if this is just a silly thing I should know how to do without the aid of the plugin :)

Cheers,
Benigno.

**Comment by vovkkk** [comment]
First of all, to keep folding work you have to maintain consistent indents (you can see expected indent for current document on right side of status-bar, e.g. `Spaces: 2` also you can change `tab_size` setting in PlainTasks user settings file so the value you would set will apply for each document when you open it) .

Second, if indented block contains more than one line, you’ll see folding buttons in gutter, but some settings may prevent it, e.g. you might hide gutter or set buttons to fade, so just review your settings if you don’t see fold buttons.

Third, there are default ST keybindings which allow to fold any indented block (even if it is one line):
<kbd>ctrl+shift+[</kbd> fold & <kbd>ctrl+shift+]</kbd> unfold (if you’re on OSX, then <kbd>⌘</kbd> instead of <kbd>ctrl</kbd>).
Also, there are keybindings to fold all blocks in the whole document by level (<kbd>⌘</kbd> if OSX)
* <kbd>ctrl+k</kbd>, <kbd>ctrl+1</kbd> — level one;
* <kbd>ctrl+k</kbd>, <kbd>ctrl+2</kbd> — level two;
* and so on up to level nine;
* <kbd>ctrl+k</kbd>, <kbd>ctrl+0</kbd> — unfold all;

    FWIW, I like these level based folding so much that [rebind](https://github.com/vovkkk/stuff/blob/master/User/Default%20%28Windows%29.sublime-keymap#L10-L19) them to more simple keystrokes <kbd>alt+number</kbd>.

**Comment by benignoc** [comment]
Hello Vova,

     Thanks a lot, that really clarifies. I am sorry I made noise here.

Best regards, and thanks a lot for your help,
Benigno.
