### ISSUE TITLE
Bug: Not all open task bullets create a new task in a new line

### ISSUE THREAD

**Issue by jemhuntr** [aziz/PlainTasks#251]
Some bullets (❑ □ ☐) behave as expected. However, for bullets like (≡ → ›), creating a new task is bugged. Instead of going to a new line and create the task there, it creates the task in the current line.

**Comment by vovkkk** [comment]
`≡ → ›` mentioned only in settigs files, never were presented in tmLanduage. So I gues it was kinda draft or something. cc @aziz 
The real question is these chars supposed to be one bullet or three different kinds, if later then it is very easy to add, if first then harder.
Another question is do we really need it? or maybe just remove its mention from settings/readme?

**Comment by jemhuntr** [comment]
personally I prefer using → or ›, because I generally think it looks nicer as a list.

**Comment by aziz** [comment]
To be honest those are there as a result of me investigating character maps for suitable bullets. They've been candidates that as @vovkkk mentioned never ended up being used in tmLanguage file. 
I inclined towards removing them from settings. The problem is that these do not go well with done or cancelled symbols. 
Another problem that makes me a bit uncomfortable is that the length of  ` → ` symbol is highly dependent on the font. In some fonts it's really long and destroys the vertical alignment of the list. 
I think @vovkkk and I are both open to change those symbols as long as you can come up with a design in plain text that looks better than what PlainTasks offers now.
