### ISSUE TITLE
Python List Indexing

### ISSUE THREAD

**Issue by NJBS** [aziz/PlainTasks#256]
Is there a particular reason you choose to reference the last index of a list with ```~0``` rather than ```-1```?

**Comment by vovkkk** [comment]
Index in Python is 0-based, i.e. first item is 0, second is 1, etc.

Hence, imo, it is more sensible to use ~0 for last one, and ~1 for second from end, etc., than -1, -2…








От: NJBS
Отправлено: ‎вторник‎, ‎17‎ ‎ноября‎ ‎2015‎ г. ‎0‎:‎22
Кому: aziz/PlainTasks





Is there a particular reason you choose to reference the last index of a list with ~0 rather than -1?
