### ISSUE TITLE
Comment: Inspiration for Future Features from Workflowy

### ISSUE THREAD

**Issue by diego898** [aziz/PlainTasks#295]
I just became aware of a online tool called workflowy. In testing it out, I think it would be a great place to draw inspiration from for possible features. One of my favorites is clicking taggs to filter lists by that tag. In addition to the seemingly endless "zooming in" on sublists. 

I still prefer open-source, text-based lists I can sync on github, but I just wanted to make you aware of this tool.

**Comment by vovkkk** [comment]
I was aware of it years ago, but did not return to it for long time.

Zooming is cool, but that’s the beauty of rich text (DOM), hardly feasible in case of raw plain-text.

Not clicking (because of inflexible mouse interactions of ST), but pressing keybinding to fold to tag is achievable easily, I’ll add it someday this/next week.

**Comment by diego898** [comment]
Shouldn't the new right click menu option be explain in the README? Also, how do you "undo" the filtering? Manually opening all the folded sections?

**Comment by vovkkk** [comment]
It is in Tutorial.todo.
I didn’t think it is necessary to mention in readme because unfold all is standard command of Sublime Text, but yeah… I was wrong

**Comment by diego898** [comment]
I meant to add the right click menu options to the readme
