### ISSUE TITLE
Bug: @started and @lasted not inserted

### ISSUE THREAD

**Issue by Mnobody** [aziz/PlainTasks#300]
I have two bugs after last updates.
Time is not inserted on "tab" after "@started". 
If i wrote time by myself "@lasted" is not calculating/not inserting.

Ubuntu 14.04 LTS
Sublime Text build 3065
PlainTasks 2016.11.16.22.35.01

**Comment by vovkkk** [comment]
You must upgrade to 3126, because the latest PT uses a new feature of ST (phantoms were added in 3118).

Or if you are against upgrade, you may replace your local files with files from [old version](https://codeload.github.com/aziz/PlainTasks/zip/4ec156e7b4fa4395f15f1857b9d52573bc7a9c58) manually and replace package-metadata.json content with

```
{"description": "An opinionated todo-list plugin for Sublime Text editor (version 2 and 3)", "url": "https://github.com/aziz/PlainTasks", "platforms": ["*"], "version": "3000.09.26.04.37.41", "sublime_text": "*", "dependencies": []}
```
so PT won’t be upgraded until 3000 year.
