### ISSUE TITLE
Disable mouse-click

### ISSUE THREAD

**Issue by Fdiang** [aziz/PlainTasks#308]
Mouse click on edit area are disabled for all files opened on Sublime. This started with version v2016.12.01.23.23.43

**Comment by vovkkk** [comment]
The latest version is  2016.12.02.16.24.36

How did you know it is PlainTasks?
What is you version of Sublime Text? OS? locale (Portuguese)?

**Comment by vovkkk** [comment]
Confirm, it is indeed still happening, but only in ST2, so for now we break support of localised dates in ST2.

**Comment by vovkkk** [comment]
Not sure if I want to fix it properly, because ISO dates are better and ST2 is becoming outdated, but if anyone want to send pull request for it feel free, I think the way to fix it can be seen in InsertDates package: move `strftime` and `strptime` to submodule in subdirectory and call setlocale in that submodule and import corresponding function from it like `date_to_string` and `string_to_date`
