### ISSUE TITLE
Menu Item (?)

### ISSUE THREAD

**Issue by sundarv85** [aziz/PlainTasks#311]
Does it make sense to also have a sublime main menu item for Tasks, just like [PlainNotes](https://github.com/aziz/PlainNotes).

**Comment by vovkkk** [comment]
I do not think so, imagine every package will have separate menu, that would be too much.

PlainNotes differs, it is a manager for notes, so it kinda make sense because it is like [almost] separate app.
PlainTasks only gives commands that work within certain files (with couple of exceptions such as new document).

Besides, if users need a menu it is very easy to create for themself, some may want it as separate menu of main one, others as submenu of View menu or Tools, or context one.

**Comment by sundarv85** [comment]
@vovkkk The problem I usually face is, I have a set of TODO files which I want to open. With PlainNotes there is an option to view the Recent Items. Such a menu could be a configurable option, which can be enabled only if users need it. Currently I have setup all my TODO files in a project and I have to open that project separately. 

If PlainNotes could have also the PlainTasks commands, that would be sufficient.

**Comment by vovkkk** [comment]
> If PlainNotes could have also the PlainTasks commands, that would be sufficient.

PlainNotes has its own bug tracker.

Also there are some packages like RecentFiles or  HistoryFiles or FilesHistory or something in Package Control.
