### ISSUE TITLE
Default key binding is the same as multiple cursors

### ISSUE THREAD

**Issue by andresmaiden** [aziz/PlainTasks#328]
The default key binding for plain_tasks_complete is the same as multiple cursors, one of the most usefull and used features of sublime. It should be other key binding by default.
I've changed it several times, but it keep coming back to ctrl+d

**Comment by vovkkk** [comment]
dup #316 



> I've changed it several times, but it keep coming back to ctrl+d

1. You have to redefine keybindings *only* in User keybinding file, because default one will be overwritten upon each update.
2. Keybinding does not define keys for command, but the opposite way: command for keys, i.e. if you set complete command to be executed by other keys in User file, then default file still has keybinding for ctrl+d, thus if you add `{ "keys": ["ctrl+d"], "command": "find_under_expand" }` to User file, then no package can change it.

**Comment by andresmaiden** [comment]
Exelent!! Thanks a lot for your time, I didn't know about the opposite way.

**Comment by rabin-io** [comment]
This answer/issue should go to a wiki/FAQ page
