### ISSUE TITLE
Custom Theme 

### ISSUE THREAD

**Issue by sundarv85** [aziz/PlainTasks#333]
Hello,

To add custom themes, I go to `Browser Packages -> PlainTasks -> add my own theme.tmTheme`. And then set it as my theme for PlainTasks.

When Sublime restarts and when PlainTasks is updated my custom theme is deleted. Is there a way to overcome this. 

Is there a defined method to add custom themes that are not lost during upgrade.

BTW: In case, you are open to adding custom themes to the standard PlainTasks, then what I'm using is: https://draculatheme.com

**Comment by vovkkk** [comment]
Standard way is keep your stuff in `Packages/User`, or you can create another subdirectory, then in settings you just set correct relative path, e.g. `Package/User/myscheme.tmTheme` or something like that.

Speaking of new schemes, generally pull requests are welcomed, on the other side we probably should not add too much because it increases size of package and during upgrade PC downloads the entire package, so... yea 1MB is not that much but if you have many packages (100 and more) and they are upgraded often that might be annoying, besides do ppl actually use every scheme? you can use only one scheme at once, right, so I dunno if we want more schemes.
But yes, generally speaking pull requests for new schemes are welcomed.

**Comment by zenorocha** [comment]
Thanks for suggesting Dracula @sundarv85!
