### ISSUE TITLE
Color of checkmark changed from green to violet ✔ 

### ISSUE THREAD

**Issue by CodingDive** [aziz/PlainTasks#430]
Yesterday I still had green checkmarks then I ran some Windows 11 updates and suddenly all my checkmarks across every .todo file became violet. Does anyone know how I could revert them back to green?

**Comment by vovkkk** [comment]
According to https://emojipedia.org/check-mark/ it is a feature of the November update of Windows 11.
I can only recommend you either to try other variations of done bullet `✓ ☑ + [x]` (see the default settings file), or you can try to ask ST devs to implement system-agnostic emoji render or whatever it is actually called, i.e. the case when emoji looks like a text rather than an image, so that way it will be coloured by the syntax highlighting.
